config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  resources :entries do
    resources :reactants
  end

  resources :reagents

  root 'home#index'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
	has_many :reactant
	has_many :reagent, through: :reactant
	validates :reaction_number, presence: true
end

app/models/reactant.rb
class Reactant < ActiveRecord::Base
  belongs_to :entry
  belongs_to :reagent
end

app/models/reagent.rb
class Reagent < ActiveRecord::Base
	has_many :reactant
	has_many :entry, through: :reactant

	validates :name, presence: true

	def reagent_name
		:name
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  respond_to :html, :js

  def index
    @entries = Entry.all
  end

  def show
  	@entry = Entry.find(params[:id])

    @reactants = Reactant.all

    @reagent = Reagent.find(params[:id])
  end

  def new
    @entry = Entry.new
  end

  def edit
    @entry = Entry.find(params[:id])
  end

  def create
    @entry = Entry.new(entry_params)

    if @entry.save
      redirect_to @entry
    else
      render 'new'
    end
  end

  def update
  	@entry = Entry.find(params[:id])
  	
  	if @entry.update_attributes(entry_params)
  		redirect_to @entry
  	else
  		render 'edit'
  	end
  end

  def destroy
    @entry = Entry.find(params[:id])

    @entry.destroy

    redirect_to entries_path
  end

  private
  	def entry_params
  		params.require(:entry).permit(:reaction_number, :starting_material, :reaction_time, :procedure)
  	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reactants_controller.rb
class ReactantsController < ApplicationController
	
	before_action :find_entry
	respond_to :html, :js

	def index
		@reactants = Reactant.all
	end

	def show
		redirect_to entry_path(:entry_id => @entry.id)
	end

	def new
		@reactant = Reactant.new({ :entry_id => @entry.id })
		@reagents = Reagent.order(name: :desc)
		@reactants = Reactant.all
	end

	def edit
		@reactant = Reactant.find(params[:id])
	end

	def create
		@reactant = Reactant.create(reactant_params)
		@reactants = Reactant.all

		if @reactant.save
			redirect_to @entry
		else
			redirect_to @entry
		end
	end

	def update
		
	end

	def destroy
		@reactant = Reactant.find(params[:id])

		if @reactant.destroy
			redirect_to entry_path(@entry.id)
		else
			redirect_to '/'
		end
	end

	private
		def reactant_params
			params.require(:reactant).permit(:starting_material, :equivalents, :reagents_id, :entry_id)
		end

	def find_entry
		if params[:entry_id]
			@entry = Entry.find(params[:entry_id])
		end
	end
end

app/controllers/reagents_controller.rb
class ReagentsController < ApplicationController
  def index
    @reagents = Reagent.all
  end

  def show
  	@reagent = Reagent.find(params[:id])
  end

  def new
    @reagent = Reagent.new
  end

  def edit
    @reagent = Reagent.find(params[:id])
  end

  def create
    @reagent = Reagent.new(reagent_params)

    if @reagent.save
      redirect_to @reagent
    else
      render 'new'
    end
  end

  def update
  	@reagent = Reagent.find(params[:id])
  	
  	if @reagent.update_attributes(reagent_params)
  		redirect_to @reagent
  	else
  		render 'edit'
  	end
  end

  def destroy
    @reagent = Reagent.find(params[:id])

    @reagent.destroy

    redirect_to reagentsCAS Number_path
  end

  private
  	def reagent_params
  		params.require(:reagent).permit(:name, :cas_num, :mol_weight, :phase, :molarity, :density)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reactants_helper.rb
module ReactantsHelper
end

app/helpers/reagents_helper.rb
module ReagentsHelper
end

app/views/entries/_form.html.erb
<div class="form_text">
	<span><%= f.label :reaction_number %></span>:
	<%= f.text_field :reaction_number %>
</div></br>

<div class="form_text">
	<span><%= f.label :reaction_time %></span>:
	<%= f.text_field :reaction_time %>
</div></br>

<div class="form_text">
	<span><%= f.label :procedure %></span>:
	<%= f.text_field :procedure %>
</div></br>

<div class="form_text">
	<%= f.submit %>
</div>

app/views/entries/_newAJAX.html.erb
<%= form_for @reactant, url: entry_reactants_path remote: true do |f| %>
	
	<div class='form_text'>
		<%= f.label :starting_material %>
		<%= f.check_box :starting_material %>
	</div></br>

	<div class='form_text'>
		<%= f.label :reagents_id %>
		<%= f.select( :reagents_id, @reagents.map { |g| [ g.name, g.id ] }) %>
	</div></br>

	<div class='form_text'>
		<%= f.label :equivalents %>
		<%= f.text_field :equivalents %>
	</div></br>

	<div class='form_text'>
		<%= f.submit %>
	</div>

<% end %>

app/views/entries/edit.html.erb
<%= render 'layouts/topnav' %>
<h2 class='title_text'>Edit Entry:</h2>

<%= form_for :entry, url: entry_path(@entry), method: :patch do |f| %>
	
	<div class="form_text">
		<span><%= f.label :reaction_number %></span>:
		<%= f.text_field :reaction_number %>
	</div></br>

	<div class="form_text">
		<span><%= f.label :reaction_time %></span>:
		<%= f.text_field :reaction_time %>
	</div></br>

	<div class="form_text">
		<span><%= f.label :procedure %></span>:
		<%= f.text_field :procedure %>
	</div></br>

	<div class="form_text">
		<%= f.submit %>
	</div>
<% end %>

app/views/entries/index.html.erb
<%= render 'layouts/topnav' %>

<h2 class='title_text'>Listing of available entries:</h2></br>

<div class='grid_frame'>

<% @entries.each do |entry| %>
	<div class='index_block'>
		
		<h4 class='title_text'>Reaction Number:</h4></br>
			<p class='title_text'><%= best_in_place entry, :reaction_number, :as => :input %></p></br>
		<h4 class='title_text'>Reaction Time:</h4></br>
			<p class='title_text'><%= entry.reaction_time %></p></br>
		<h4 class='title_text'>Procedure:</h4></br>
			<p class='title_text'><%= entry.procedure %></p></br>
		
		<p class='title_text'><%= link_to 'View Entry', entry_path(entry) %></p>

		<p class='title_text'><%= link_to 'Edit Entry', edit_entry_path(entry) %>
		</p>

		<p class='title_text'><%= link_to 'Delete Entry', entry_path(entry),
			method: :delete,
			data: { confirm: 'Are you sure that you want to delete this entry?' } %></p>
	</div>
<% end %>

</div>

app/views/entries/new.html.erb
<%= render 'layouts/topnav' %>

<h2 class= 'title_text'>New Entry:</h2>

<%= form_for :entry, url: entries_path do |f| %>
	
	<div class="form_text">
		<span><%= f.label :reaction_number %></span>:
		<%= f.text_field :reaction_number %>
	</div></br>

	<div class="form_text">
		<span><%= f.label :reaction_time %></span>:
		<%= f.text_field :reaction_time %>
	</div></br>

	<div class="form_text">
		<span><%= f.label :procedure %></span>:
		<%= f.text_field :procedure %>
	</div></br>

	<div class="form_text">
		<%= f.submit %>
	</div>
<% end %>

app/views/entries/show.html.erb
<%= render 'layouts/topnav' %>

<div class='reaction_frame'>

	<div class='entry_panel left'>

		<h1>Show Entry:</h1>
		
		<p>
			<strong>Reaction Number:</strong>
			<%= @entry.reaction_number %>
		</p>
		
		<p>
			<strong>Reaction Time:</strong>
			<%= @entry.reaction_time %>
		</p>

		<p>
			<strong>Solvent:</strong>
			<%= @entry.solvent %>
		</p>
		
		<p>
			<strong>Procedure:</strong>
			<%= @entry.procedure %>
		</p>

		<div class='inline_button'>	

			<%= link_to new_entry_reactant_path(@entry.id), remote: true do %>
				<button>Add reagents to this entry...</button>
			<% end %>
			<div class='left_entry_container' id='task_form' style='display: none;'>
			</div>

		</div>
	
	</div>

	<div class='entry_panel right' id='reactants'>


		<%= render 'reactants/index' %>

	</div>

</div>

app/views/home/index.html.erb
<%= render 'layouts/topnav' %>
<span>
	<h2>Welcome to Syn-Quivalents!</h2>

	<p>Syn-Quivalents is a tool designed by and for Chemists who need to keep neat and organized their important Synthesis reactions.</p>

	<p>Syn-Quivalents is being built to address the following issues that Synthesis encounters on a daily basis:</p>

	<ul>
		<li>Track and record experimental data</li>
		<li>Retrieve experimental properties of compounds via CAS numbers</li>
		<li>Automatically calculate masses and volumes of reagents from equivalent values</li>
	</ul>
</span>

app/views/layouts/_form.html.erb
<%= form_for '@entry', url: '/entry/' do |f| %>
	
	<div class="form_text">
		<span><%= f.label :reaction_number %></span>:
		<%= f.text_field :reaction_number %>
	</div>



	<div class="form_text">
		<%= f.submit %>
	</div>
<%= :starting_material => nil %>
<%= :reaction_time => nil %>
<%= :procedure => nil %>
<% end %>

app/views/layouts/_form_full.html.erb
	<div class="form_text">
		<span><%= f.label :reaction_number %></span>:
		<%= f.text_field :reaction_number %>
	</div></br>

	<div class="form_text">
		<span><%= f.label :starting_material %></span>:
		<%= f.text_field :starting_material %>
	</div></br>

	<div class="form_text">
		<span><%= f.label :reaction_time %></span>:
		<%= f.text_field :reaction_time %>
	</div></br>

	<div class="form_text">
		<span><%= f.label :procedure %></span>:
		<%= f.text_field :procedure %>
	</div></br>

	<div class="form_text">
		<%= f.submit %>
	</div>

app/views/layouts/_topnav.html.erb
<div class="topNav">
	<div class="container">
		<nav class="logo">
			<h2 class="title"><%= link_to 'Syn-', '/' %></h1>
		</nav>
			<h2 style= "margin-left: 5px" class="title">Quivalents</h1>
		<nav class="dash">
			<div class="button">
				<h3>Login</h3>
			</div>
			<div class="button" id='reagent_button'>
				<h3><%= link_to "Reagent Library", reagents_path %></h3>
			</div>
			<div class="button">
				<h3><%= link_to "Show Entries", entries_path %></h3>
			</div>
			<div class="button">
				<h3><%= link_to "New Entry", new_entry_path %></h3>
			</div>
		</nav>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Synquivalents</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reactants/_index.html.erb
<div id='reactants_start_mat'>
<h2>Starting Material:</h2>
	<% @reactants.where( starting_material: true ).each do |start_mat| %>
		
		<% @reagent = Reagent.find_by(id: start_mat.reagent_id) %>
		<div class='entry_container'>
		<h3 class='title_text'>Reactant Name:</h3>
			<p class='title_text'><%= @reagent.name %></p>
		<h3 class='title_text'>Equivalents:</h3>
			<p class='title_text'><%= start_mat.equivalents %></p>
		<%= link_to 'Delete Reactant', entry_reactant_path({:id => start_mat.id, :entry_id => @entry.id}),
		method: :delete,
		data: { confirm: 'Are you shure that you want to delete this reactant?' } %>
		</div>
	<% end%>
	
</div>

<div id='reactants_others'>
<h2>Reactants:</h2>
	<% @reactants.where( starting_material: false ).each do |other| %>
	
		<% @reagent = Reagent.find_by(id: other.reagent_id) %>
		<div class='entry_container'>
		<h3 class='title_text'>Reactant Name:</h3>
			<p class='title_text'><%= @reagent.name %></p>
		<h3 class='title_text'>Equivalents:</h3>
			<p class='title_text'><%= other.equivalents %></p>
		<%= link_to 'Delete Reactant', entry_reactant_path({:id => other.id, :entry_id => @entry.id}),
		method: :delete,
		data: { confirm: 'Are you shure that you want to delete this reactant?' } %>
		</div>
	<% end%>

</div>

app/views/reactants/_new.html.erb
<%= form_for @reactant, url: entry_reactants_path, remote: true do |f| %>
	
	<div class='form_text'>
		<%= f.label :starting_material %>
		<%= f.check_box :starting_material %>
	</div></br>

	<div class='form_text'>
		<%= f.label :reagent_id %>
		<%= f.select( :reagent_id, @reagents.map { |g| [ g.name, g.id ] }) %>
	</div></br>

	<div class='form_text'>
		<%= f.label :equivalents %>
		<%= f.text_field :equivalents %>
	</div></br>

	<div class='form_text'>
		<%= f.submit %>
	</div>

<% end %>

app/views/reactants/_save.js.erb
$('#reactants').html( "<%= escape_javascript(render 'reactants/index') %>" );
$('#task_form').slideUp(350);

app/views/reactants/backup_index.html.erb
<div>

	<h3 class='title_text'>Starting Material:</h3>
		<p class='title_text'><%= @start_mat_print %></p>
	

</div>

<div>

	<% @reactants.each do |other| %>

		<% if other.starting_material != true then %>

			<h3 class='title_text'>Reactant Name:</h3>
				<p class='title_text'><%= other.reagents_id %></p>
			<h3 class='title_text'>Equivalents:</h3>
				<p class='title_text'><%= other.equivalents %></p>
		<% end %>
			<%= link_to 'Delete Reactant', entry_reactant_path(:entry_id => @entry.id),
			method: :delete,
			data: { confirm: 'Are you shure that you want ot delete this reactant?' } %>

	<% end%>

</div>

app/views/reactants/backup_new.html.erb
<%= render 'layouts/topnav' %>
<h2 class='title_text'>Add Reactant to Entry:</h2>

<%= form_for @reactant, url: entry_reactants_path do |f| %>
	
	<div class='form_text'>
		<%= f.label :starting_material %>
		<%= f.check_box :starting_material %>
	</div></br>

	<div class='form_text'>
		<%= f.label :reagents_id %>
		<%= f.select( :reagents_id, @reagents.map { |g| [ g.name, g.id ] }) %>
	</div></br>

	<div class='form_text'>
		<%= f.label :equivalents %>
		<%= f.text_field :equivalents %>
	</div></br>

	<div class='form_text'>
		<%= f.submit %>
	</div>

<% end %>

app/views/reactants/create.js.erb
$('#reactants').html( "<%= escape_javascript(render 'reactants/index') %>" );
$('#task_form').slideUp(350);

app/views/reactants/new.js.erb
$('#task_form').html("<%= escape_javascript(render 'new') %>");
$('#task_form').slideDown(350);
$('#task_form').on('ajax:success', (e, data, status, xhr), function() {
	$('#reactants').html( "<%= escape_javascript(render 'reactants/index') %>" );
	$('#task_form').slideUp(350);
});

app/views/reagents/edit.html.erb
<h1>Reagents#edit</h1>
<p>Find me in app/views/reagents/edit.html.erb</p>

app/views/reagents/index.html.erb
<%= render 'layouts/topnav' %>

<h2>Reagent Library:</h2>

<div class='grid_frame'>

<% @reagents.each do |reagent| %>
	<div class='index_block'>
		
		<h3 class='title_text'>Reagent Name:</h3></br>
			<p class='title_text'><%= reagent.name %></p></br>
		<h4 class='title_text'>CAS Number:</h4></br>
			<p class='title_text'><%= reagent.cas_num %></p></br>
		<h4 class='title_text'>Molecular Weight:</h4></br>
			<p class='title_text'><%= reagent.mol_weight %></p></br>
		<h4 class='title_text'>Phase:</h4></br>
			<p class='title_text'><%= reagent.phase %></p></br>
		<h4 class='title_text'>Density:</h4></br>
			<p class='title_text'><%= reagent.density %></p></br>
		<p class='title_text'><%= link_to 'View', reagent_path(reagent) %></p>

		<p class='title_text'><%= link_to 'Edit', edit_reagent_path(reagent) %>
		</p>

		<p class='title_text'><%= link_to 'Delete', reagent_path(reagent),
			method: :delete,
			data: { confirm: 'Are you sure that you want to delete this reagent?' } %></p>
	</div>
<% end %>

</div>

app/views/reagents/new.html.erb
<h1>Reagents#new</h1>
<p>Find me in app/views/reagents/new.html.erb</p>

app/views/reagents/show.html.erb
<h1>Reagents#show</h1>
<p>Find me in app/views/reagents/show.html.erb</p>